@extends('front.layouts.app')
@section('title', 'Certificate Preview - Dialogika')
@section('content')
    <x-navigation-auth />

    <main class="flex flex-col pb-10 mt-[30px]">
        <section class="flex flex-col w-full max-w-[1000px] mx-auto">
            <div class="flex items-center mb-5">
                <a href="{{ route('dashboard.certificates') }}" class="flex items-center gap-2 text-obito-text-secondary hover:text-obito-black transition-all duration-300">
                    <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                    </svg>
                    <span>Back to Certificates</span>
                </a>
            </div>
            
            <div class="certificate-preview bg-white p-[30px] rounded-[20px] shadow-lg">
                <div class="preview-container mx-auto">
                    <div class="certificate-container">
                        <div class="background-shape top-left"></div>
                        <div class="background-shape bottom-right"></div>
                        <img src="{{ asset('assets/images/logos/logo-64-big.png') }}" alt="Logo" class="logo">
                        <h1 class="certificate-header">Certificate of Completion</h1>
                        <p class="certificate-subtitle">This certificate is awarded to</p>
                        <h2 class="certificate-name">{{ $userName }}</h2>
                        <p class="certificate-subtitle">For successfully completing the course:</p>
                        <h3 class="certificate-course">{{ $courseName }}</h3>
                        <p class="certificate-date">Completed on: {{ $completionDate }}</p>
                        <div class="decorative-line"></div>
                        <p class="certificate-description">
                            In recognition of your dedication and hard work in completing this course. Your efforts have demonstrated a commitment to learning and growth.
                        </p>
                        <div class="signature">
                            {{ $mentorName }}
                            <div class="signature-line"></div>
                        </div>
                        <p class="mentor-title">Mentor</p>
                        <p class="footer-note">This certificate is generated by Dialogika Public Speaking Online Course</p>
                    </div>
                </div>
            </div>
            
            <div class="flex justify-center mt-5">
                <a href="{{ route('courses.certificate', $course) }}" class="py-2 px-5 bg-obito-green text-white rounded-full hover:drop-shadow-effect transition-all duration-300">
                    <span class="font-semibold">Download PDF Certificate</span>
                </a>
            </div>
        </section>
    </main>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Alex+Brush&display=swap');
        
        .preview-container {
            max-width: 750px;
            position: relative;
        }
        
        .certificate-container {
            position: relative;
            background-color: #ffffff;
            border: 10px solid #2f6a62;
            border-radius: 20px;
            padding: 20px;
            width: 650px;
            min-height: 880px;
            text-align: center;
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
            margin: 0 auto;
        }
        
        .certificate-header {
            font-size: 24pt;
            font-weight: bold;
            color: #2f6a62;
            margin-bottom: 10px;
            text-transform: uppercase;
        }
        
        .certificate-subtitle {
            font-size: 14pt;
            color: #6a6f7c;
            margin-bottom: 15px;
        }
        
        .certificate-name {
            font-size: 22pt;
            font-weight: bold;
            color: #0a0723;
            margin-bottom: 15px;
        }
        
        .certificate-course {
            font-size: 16pt;
            color: #2f6a62;
            font-weight: bold;
            margin-bottom: 15px;
        }
        
        .certificate-date {
            font-size: 12pt;
            color: #6a6f7c;
            margin-bottom: 30px;
        }
        
        .decorative-line {
            width: 60%;
            height: 2px;
            background-color: #2f6a62;
            margin: 20px auto;
        }
        
        .certificate-description {
            font-size: 12pt;
            color: #6a6f7c;
            margin-bottom: 30px;
            line-height: 1.5;
        }
        
        .signature {
            margin-top: 20px;
            font-size: 18pt;
            color: #6a6f7c;
            font-family: 'Alex Brush', cursive;
            text-align: center;
        }
        
        .signature-line {
            margin-top: 10px;
            border-top: 1px solid #2f6a62;
            width: 200px;
            margin-left: auto;
            margin-right: auto;
        }
        
        .mentor-title {
            color: #6a6f7c;
            margin-top: 5px;
        }
        
        .logo {
            width: 80px;
            margin: 0 auto 20px;
        }
        
        .footer-note {
            font-size: 10pt;
            color: #6a6f7c;
            margin-top: 20px;
        }
        
        .background-shape {
            position: absolute;
            width: 250px;
            height: 250px;
            background: #2f6a62;
            border-radius: 50%;
            opacity: 0.1;
            z-index: 0;
        }
        
        .background-shape.top-left {
            top: -50px;
            left: -50px;
        }
        
        .background-shape.bottom-right {
            bottom: -50px;
            right: -50px;
        }
    </style>
@endsection